# -*- coding: utf-8 -*-
"""SIT771_Task9_1c.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYOhnL4c9DNmUORSJe7U1TQz_DMwbjiz
"""

class Account:

    def __init__(self, name, startingBalance):
      self.name = name
      self.balance = startingBalance

    def print_account(self):
      print("%s $%.2f" % (self.name, self.balance))

    def withdraw(self, amount_to_withdraw):
      if amount_to_withdraw < 0:
        print("ERROR: PLEASE ENTER A POSITIVE NUMBER. WITHDRAWAL CANNOT BE PROCESSED")
        return False
      elif amount_to_withdraw > self.balance:
        print("ERROR: INSUFFICIENT FUNDS. WITHDRAWAL CANNOT BE PROCESSED")
        return False
      else:
        self.balance -= amount_to_withdraw
        return True

    def deposit(self, amount_to_deposit):
      if amount_to_deposit > 0:
        self.balance += amount_to_deposit
        return True
      else:
        print("INVALID DEPOSIT AMOUNT. PLEASE ENTER A POSITIVE AMOUNT")
        return False


account_1 = Account("Fred", 100.0)
account_1.print_account()

account_2 = Account("Jane", 80.0)
account_2.print_account()

while True:

  print()
  print("Select a number:")
  print("1. Print Account")
  print("2. Deposit")
  print("3. Withdraw")
  print("4. Quit")
  try:
    line = input("Select an option: ")
    num = int(line)

    if num == 1:
      account_1.print_account()
      account_2.print_account()
    elif num == 2:
      name = input("select account name: ")
      if name.upper() == "FRED":
        try:
          amount_deposit = float(input("select amount to deposit: "))
          account_1.deposit(amount_deposit)
          account_1.print_account()
        except ValueError:
          print("ERROR: PLEASE ENTER A VALID NUMBER.")
      elif name.upper() == "JANE":
        try:
          amount_deposit = float(input("select amount to deposit: "))
          account_2.deposit(amount_deposit)
          account_2.print_account()
        except ValueError:
          print("ERROR: PLEASE ENTER A VALID NUMBER.")
      else:
        print("Account name is not available.")
    elif num == 3:
      name = input("select account name: ")
      if name.upper() == "FRED":
        try:
          amount_withdraw = float(input("select amount to withdraw: "))
          account_1.withdraw(amount_withdraw)
          account_1.print_account()
        except ValueError:
          print("ERROR: PLEASE ENTER A VALID NUMBER.")
      elif name.upper() == "JANE":
        try:
          amount_withdraw = float(input("select amount to withdraw: "))
          account_2.withdraw(amount_withdraw)
          account_2.print_account()
        except ValueError:
          print("ERROR: PLEASE ENTER A VALID NUMBER.")
      else:
        print("Account name is not available.")
    elif num == 4:
      break
    else:
      print("CHOOSE A NUMBER BETWEEN 1-4")
  except ValueError:
      print("INVALID INPUT. PLEASE INPUT A NUMBER BETWEEN 1-4.")